Traceback (most recent call last):
  File "ThunderMovie/douban_movie.py", line 5, in <module>
    import django
ImportError: No module named django
nohup: python3: No such file or directory
nohup: /usr/bin/python3: No such file or directory
douban_movie -i <input>
WARNING:root: get_movie_base_information is ready to start.
Traceback (most recent call last):
  File "ThunderMovie/douban_movie.py", line 165, in <module>
    main(sys.argv[1:])
  File "ThunderMovie/douban_movie.py", line 161, in main
    di.get_movie_base_information()
  File "ThunderMovie/douban_movie.py", line 30, in get_movie_base_information
    if start:
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/connections.py", line 1292, in read
    self._read_result_packet(first_packet)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/connections.py", line 1347, in _read_result_packet
    self._read_rowdata_packet()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/connections.py", line 1381, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/connections.py", line 956, in _read_packet
    recv_data = self._read_bytes(bytes_to_read)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/connections.py", line 972, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socket.py", line 378, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
WARNING:root: get_movie_base_information is ready to start.
WARNING:root:id为：19948的电影从豆瓣获取成功
WARNING:root:id为：19949的电影从豆瓣获取成功
WARNING:root:id为：19950的电影从豆瓣获取成功
WARNING:root:id为：19951的电影从豆瓣获取成功
WARNING:root:id为：19952的电影从豆瓣获取成功
WARNING:root:id为：19953的电影从豆瓣获取成功
WARNING:root:id为：19954的电影从豆瓣获取成功
WARNING:root:id为：19955的电影从豆瓣获取成功
WARNING:root:id为：19956的电影从豆瓣获取成功
WARNING:root:id为：19957的电影从豆瓣获取成功
WARNING:root:id为：19958的电影从豆瓣获取成功
WARNING:root:id为：19959的电影从豆瓣获取成功
WARNING:root:id为：19960的电影从豆瓣获取成功
WARNING:root:id为：19961的电影从豆瓣获取成功
WARNING:root:id为：19962的电影从豆瓣获取成功
WARNING:root:id为：19963的电影从豆瓣获取成功
WARNING:root:id为：19964的电影从豆瓣获取成功
WARNING:root:id为：19965的电影从豆瓣获取成功
WARNING:root:id为：19966的电影从豆瓣获取成功
WARNING:root:id为：19967的电影从豆瓣获取成功
WARNING:root:id为：19968的电影从豆瓣获取成功
WARNING:root:id为：19969的电影从豆瓣获取成功
WARNING:root:id为：19970的电影从豆瓣获取成功
WARNING:root:id为：19971的电影从豆瓣获取成功
WARNING:root:id为：19972的电影从豆瓣获取成功
WARNING:root:id为：19973的电影从豆瓣导出失败！
WARNING:root:id为：19974的电影从豆瓣获取成功
WARNING:root:id为：19975的电影从豆瓣获取成功
WARNING:root:id为：19976的电影从豆瓣获取成功
WARNING:root:id为：19977的电影从豆瓣获取成功
WARNING:root:id为：19978的电影从豆瓣导出失败！
WARNING:root:id为：19979的电影从豆瓣获取成功
WARNING:root:id为：19980的电影从豆瓣获取成功
WARNING:root:id为：19981的电影从豆瓣获取成功
WARNING:root:id为：19982的电影从豆瓣获取成功
WARNING:root:id为：19983的电影从豆瓣获取成功
WARNING:root:id为：19984的电影从豆瓣获取成功
WARNING:root:id为：19985的电影从豆瓣获取成功
WARNING:root:id为：19986的电影从豆瓣获取成功
WARNING:root:id为：19987的电影从豆瓣获取成功
WARNING:root:id为：19988的电影从豆瓣获取成功
WARNING:root:id为：19989的电影从豆瓣获取成功
